name: Assign Discord Role

on:
  workflow_call:
    inputs:
      ACTOR:
        required: true
        type: string
      GITHUB_EVENT_NAME:
        required: true
        type: string
      GITHUB_EVENT_ACTION:
        required: true
        type: string
    secrets:
      DISCORD_BOT_TOKEN:
        required: true
      GOOGLE_CREDENTIALS_JSON:
        required: true
      GOOGLE_SHEET_ID:
        required: true
      GUILD_ID:
        required: true
      ROLE_ID_PR:
        required: true
      ROLE_ID_ISSUE:
        required: true
      ROLE_ID_COMMIT:
        required: true

jobs:
  assign-role:
    runs-on: ubuntu-latest
    steps:
      - name: Log Start of Workflow
        run: echo "🚀 Starting Assign Discord Role Workflow"

      - name: Log Inputs
        run: |
          echo "🔹 ACTOR: ${{ inputs.ACTOR }}"
          echo "🔹 GITHUB_EVENT_NAME: ${{ inputs.GITHUB_EVENT_NAME }}"
          echo "🔹 GITHUB_EVENT_ACTION: ${{ inputs.GITHUB_EVENT_ACTION }}"

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install

      - name: Log Before Running Script
        run: echo "🛠 Running assign_discord_role.js"

      - name: Assign Discord Role
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
          GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
          ACTOR: ${{ inputs.ACTOR }}
          GUILD_ID: ${{ secrets.GUILD_ID }}
          ROLE_ID_PR: ${{ secrets.ROLE_ID_PR }}
          ROLE_ID_ISSUE: ${{ secrets.ROLE_ID_ISSUE }}
          ROLE_ID_COMMIT: ${{ secrets.ROLE_ID_COMMIT }}
          GITHUB_EVENT_NAME: ${{ inputs.GITHUB_EVENT_NAME }}
          GITHUB_EVENT_ACTION: ${{ inputs.GITHUB_EVENT_ACTION }}
        run: node scripts/assign_discord_role.js

      - name: Log Completion
        run: echo "✅ Finished Running assign_discord_role.js"
