name: Assign Discord Role (Local Test)

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
  issues:
    types: [opened]

jobs:
  assign-role:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Debug Repository Structure
        run: ls -R

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install

      - name: Assign Discord Role
        run: node scripts/assign_discord_role.js
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          FIREBASE_CREDENTIALS_JSON: ${{ secrets.FIREBASE_CREDENTIALS_JSON }}
          ACTOR: ${{ github.actor }}
          GUILD_ID: ${{ secrets.GUILD_ID }}
          ROLE_ID_PR_1: ${{ secrets.ROLE_ID_PR_1 }}
          ROLE_ID_PR_5: ${{ secrets.ROLE_ID_PR_5 }}
          ROLE_ID_PR_10: ${{ secrets.ROLE_ID_PR_10 }}
          ROLE_ID_ISSUE_1: ${{ secrets.ROLE_ID_ISSUE_1 }}
          ROLE_ID_ISSUE_5: ${{ secrets.ROLE_ID_ISSUE_5 }}
          ROLE_ID_COMMIT_1: ${{ secrets.ROLE_ID_COMMIT_1 }}
          ROLE_ID_COMMIT_15: ${{ secrets.ROLE_ID_COMMIT_15 }}
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          GITHUB_EVENT_ACTION: ${{ github.event.action || '' }}
